services:
  api:
    image: dosgato-api-local
    pull_policy: build
    build:
      context: ${DOSGATO_API_PATH:-../dosgato}
  render:
    image: dosgato-render-local
    pull_policy: build
    build:
      context: ${DOSGATO_RENDER_PATH:-../dosgato-render}
