services:
  proxy:
    image: nginx:alpine
    attach: false
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  ui:
    build:
      context: .
    attach: false
    environment:
      API_BASE: http://proxy/.api
      RENDER_BASE: http://proxy
      AUTH_REDIRECT: http://fakeauth/login?clientId=dosgato-admin&returnUrl=http%3A%2F%2Fproxy%2F.admin
      ADMIN_ALLOW_HOST_REGEX: 'proxy|ui'
  api:
    build:
      context: ../dosgato
    attach: false
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: development
      TZ: America/Chicago
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatodev
      MYSQL_HOST: mysql
      RESET_DB_ON_STARTUP: 'true'
      JWT_TRUSTED_ISSUERS: '[{ "iss": "unified-auth", "url": "http://fakeauth/jwks" }, { "iss": "dg-render", "secret": "rendertoken" }]'
  render:
    build:
      context: ../dosgato-render
    attach: false
    environment:
      NODE_ENV: development
      DOSGATO_RENDER_JWT_SECRET: rendertoken
      DOSGATO_API_BASE: http://proxy/.api
      DOSGATO_ADMIN_BASE: http://proxy/.admin
  fakeauth:
    image: registry.its.txstate.edu/unified-auth-stub:dev
    attach: false
  mysql:
    image: mariadb
    command: --max_allowed_packet=32505856
    attach: false
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatodev
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - dosgatodbtest:/var/lib/mysql
  testing-container:
     build:
       context: test
     attach: true
     environment:
       API_BASE: http://proxy/.api
       RENDER_BASE: http://proxy
       DOSGATO_ADMIN_BASE: http://proxy/.admin
     volumes:
       - ./test/test-results:/test-results
volumes:
  dosgatodbtest: {}
  dosgatofilestest: {}
