services:
  dosgato-admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    environment:
      API_BASE: http://localhost
      RENDER_BASE: http://localhost:3002
      AUTH_REDIRECT: http://localhost:3001/login?clientId=dosgato-admin&returnUrl=http%3A%2F%2Flocalhost%3A3000%2Fadmin
      TRACING_SERVER: http://localhost:8200
    volumes:
      - ./src:/usr/app/src
      - ./static:/usr/app/static
      - ./svelte.config.js:/usr/app/svelte.config.js
      - ./vite.config.js:/usr/app/vite.config.js
  dosgato-api:
    build:
      context: ../dosgato
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 9229:9229
    environment:
      NODE_ENV: development
      TZ: America/Chicago
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatodev
      MYSQL_HOST: mysql
      RESET_DB_ON_STARTUP: 'true'
      JWT_TRUSTED_ISSUERS: '[{ "iss": "unified-auth", "url": "http://fakeauth/jwks" }, { "iss": "dg-render", "secret": "rendertoken" }]'
    volumes:
      - dosgatofiles:/files
      - ../dosgato/src:/usr/app/src
      - ../dosgato/testserver:/usr/app/testserver
      - ../dosgato/bootstrap:/bootstrap
      - ../dosgato/test/files/blankpdf.pdf:/files/storage/P/K/BUoghpogATqmK14ry1wqKsP-e-S8GVqHKuCxH7k1k
      - ../dosgato/test/files/bobcat.jpg:/files/storage/Q/7/HN1moFtRWxE_gLyvxM8B2sK5CrjB3482LttjgbWME
    depends_on:
      - mysql
  dosgato-resizer:
    image: registry.its.txstate.edu/dosgato-resizer:qual
    environment:
      TZ: America/Chicago
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatodev
      MYSQL_HOST: mysql
    volumes:
      - dosgatofiles:/files
      - ../dosgato/test/files/blankpdf.pdf:/files/storage/P/K/BUoghpogATqmK14ry1wqKsP-e-S8GVqHKuCxH7k1k
      - ../dosgato/test/files/bobcat.jpg:/files/storage/Q/7/HN1moFtRWxE_gLyvxM8B2sK5CrjB3482LttjgbWME
    depends_on:
      - mysql
  dosgato-render:
    build:
      context: ../dosgato-render
    ports:
      - 3002:80
    environment:
      NODE_ENV: development
      DOSGATO_RENDER_JWT_SECRET: rendertoken
      DOSGATO_ADMIN_BASE: http://localhost:3000/.admin
      DOSGATO_API_BASE: http://dosgato-api
    volumes:
      - ../dosgato-render/src:/usr/app/src
      - ../dosgato-render/test:/usr/app/test
    depends_on:
      - dosgato-api
  fakeauth:
    image: registry.its.txstate.edu/unified-auth-stub:dev
    ports:
      - 3001:80
  mysql:
    image: percona/percona-server:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatodev
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
    volumes:
      - dosgatodb:/var/lib/mysql
volumes:
  dosgatodb: {}
  dosgatofiles: {}
