FROM node:16
FROM mcr.microsoft.com/playwright:v1.38.1-focal
 
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/

RUN apt-get update && apt-get -y install libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev
RUN npm install

COPY tests/ /app/tests/
COPY tsconfig.json /app/
COPY playwright.config.js /app/

ENTRYPOINT [ "npm" ]
CMD ["test"]
